//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public string username { get; set; }
        public string user_passward { get; set; }
        public string user_email { get; set; }
        public string user_age { get; set; }
        public string user_gender { get; set; }
        public string user_subject { get; set; }
        public string user_role { get; set; }
    }
}
